[package]
name = "rust-p2p-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p256 = { features = ["ecdh"] }
hex="0.4.3"
rand_core="0.6.3"