[package]
name = "mongo_qs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.8.1"
mongodb = "2.8.0"
serde = "1.0.194"
tokio = "1.35.1"
