[package]
name = "deltalake_hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltalake = "0.16.2"
futures = "0.3.29"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

